/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.PersonalInformation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yash
 */
public class AddPersonalInformation extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final Enterprise enterprise;

    /**
     * Creates new form AddPersonalInformation
     */
    public AddPersonalInformation(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        this.userProcessContainer= userProcessContainer;
        this.account= account;
        this.enterprise= enterprise;
        
        initComponents();
        fillData();
    }
    public void fillData(){
        nameTextField.setText(account.getPersonalInformation().getName());
        addressTextField.setText(account.getPersonalInformation().getAddress());
        contectNumTextField.setText(Long.toString(account.getPersonalInformation().getContactNum()));
        emailTextField.setText(account.getPersonalInformation().getEmailAddress());
        ImageIcon image=new ImageIcon(account.getPersonalInformation().getPhoto());
        image.setImage(image.getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        label.setIcon(image);
        
        nameTextField.setEnabled(false);
        addressTextField.setEnabled(false);
        contectNumTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        SubmitjButton. setEnabled(false);
        uploadjButton.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contectNumTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        SubmitjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        uploadjButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        nameTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 180, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Address :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 20));

        addressTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 180, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        contectNumTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add(contectNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 180, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Email Address :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        emailTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 180, -1));

        SubmitjButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SubmitjButton.setText("Submit");
        SubmitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitjButtonActionPerformed(evt);
            }
        });
        add(SubmitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        backJButton.setBackground(new java.awt.Color(255, 255, 255));
        backJButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(251, 251, 251));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        uploadjButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        uploadjButton.setText("Upload Picture");
        uploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadjButtonActionPerformed(evt);
            }
        });
        add(uploadjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));
        add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 180, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Image/personal info.jpg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void SubmitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitjButtonActionPerformed
       try {
           String patientName = nameTextField.getText();
            String address = addressTextField.getText();
            long phone = Long.parseLong(contectNumTextField.getText());
            String email=emailTextField.getText();
            boolean flag = true;
            if (email.equals("") || address.equals("") || patientName.equals("")) {
                JOptionPane.showMessageDialog(null, "values cannot be blank", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
            } else if (patientName.equals("")) {
                JOptionPane.showMessageDialog(null, "Patient Name cannot be blank", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
            } else if (address.equals("")) {
                JOptionPane.showMessageDialog(null, "Patient Address cannot be blank", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
            } else if (contectNumTextField.getText().length() > 10 || contectNumTextField.getText().length() < 10) {
                JOptionPane.showMessageDialog(null, "Phone Number cannot be more or less than 10 digits", "Invalid value Error", JOptionPane.WARNING_MESSAGE);
            }
              else if(flag){  
           account.AddPersonalInformation(patientName,address,phone,email);
           JOptionPane.showMessageDialog(null, "Successfully added Personal Information");
           
        nameTextField.setEnabled(false);
        addressTextField.setEnabled(false);
        contectNumTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        SubmitjButton.setEnabled(false);
           btnUpdate.setEnabled(true);  ;
        
              }
       }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter value in the fields", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_SubmitjButtonActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        nameTextField.setEnabled(true);
        addressTextField.setEnabled(true);
        contectNumTextField.setEnabled(true);
        emailTextField.setEnabled(true);
        btnUpdate.setEnabled(false);
        SubmitjButton.setEnabled(true);
        uploadjButton.setEnabled(true);
        
       
      
            
       
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void uploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadjButtonActionPerformed
//        // TODO add your handling code here:
//        JFileChooser a = new JFileChooser();
//           a.showOpenDialog(null);
//           File f=a.getSelectedFile();
//           String filename = f.getAbsolutePath();
//          //String filename="ABCD";
//          
//         ImageIcon icon=new ImageIcon(new ImageIcon(filename).getImage());
//         account.getPersonalInformation().setPhoto(filename);
//         label.setIcon(icon);
//         
         String path=new String();
        JFileChooser chooser=new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i=chooser.showOpenDialog(null);
        if(i == chooser.APPROVE_OPTION){
            path = chooser.getSelectedFile().getAbsolutePath();
            account.getPersonalInformation().setPhoto(path);
            label.setText("Image Uploaded");
        }else{
            JOptionPane.showMessageDialog(null, "No file Selected");
        }
        ImageIcon image=new ImageIcon(path);
        image.setImage(image.getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        label.setIcon(image);
        
    
         JOptionPane.showMessageDialog(null, "Patient picture has been uploaded !!!!");
    }//GEN-LAST:event_uploadjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitjButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField contectNumTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton uploadjButton;
    // End of variables declaration//GEN-END:variables
}
