/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.PersonalInformation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yash
 */
public class AddPersonalInformation extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final UserAccount account;
    private final Enterprise enterprise;

    /**
     * Creates new form AddPersonalInformation
     */
    public AddPersonalInformation(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        this.userProcessContainer= userProcessContainer;
        this.account= account;
        this.enterprise= enterprise;
        
        initComponents();
        fillData();
    }
    public void fillData(){
        nameTextField.setText(account.getPersonalInformation().getName());
        addressTextField.setText(account.getPersonalInformation().getAddress());
        contectNumTextField.setText(Long.toString(account.getPersonalInformation().getContactNum()));
        emailTextField.setText(account.getPersonalInformation().getEmailAddress());
        
        nameTextField.setEnabled(false);
        addressTextField.setEnabled(false);
        contectNumTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contectNumTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        SubmitjButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        nameTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 150, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Address :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        addressTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        add(addressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        contectNumTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add(contectNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 180, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Email Address :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        emailTextField.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, -1));

        SubmitjButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SubmitjButton.setText("Submit");
        SubmitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitjButtonActionPerformed(evt);
            }
        });
        add(SubmitjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(251, 251, 251));
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void SubmitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitjButtonActionPerformed
       try {
           String patientName = nameTextField.getText();
            String address = addressTextField.getText();
            long phone = Long.parseLong(contectNumTextField.getText());
            String email=emailTextField.getText();
            boolean flag = true;
            if (email.equals("") || address.equals("") || patientName.equals("")) {
                JOptionPane.showMessageDialog(null, "values cannot be blank", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
            } else if (patientName.equals("")) {
                JOptionPane.showMessageDialog(null, "Patient Name cannot be blank", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
            } else if (address.equals("")) {
                JOptionPane.showMessageDialog(null, "Patient Address cannot be blank", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
            } else if (contectNumTextField.getText().length() > 10 || contectNumTextField.getText().length() < 10) {
                JOptionPane.showMessageDialog(null, "Phone Number cannot be more or less than 10 digits", "Invalid value Error", JOptionPane.WARNING_MESSAGE);
            }
              else if(flag){  
           account.AddPersonalInformation(patientName,address,phone,email);
           JOptionPane.showMessageDialog(null, "Successfully added Personal Information");
           
        nameTextField.setEnabled(false);
        addressTextField.setEnabled(false);
        contectNumTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        
              }
       }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter value in the fields", "Empty Field Error", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_SubmitjButtonActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        nameTextField.setEnabled(true);
        addressTextField.setEnabled(true);
        contectNumTextField.setEnabled(true);
        emailTextField.setEnabled(true);
        btnUpdate.setEnabled(false);
        
       
      
            
       
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitjButton;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField contectNumTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
