/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.Role.Role;
import Business.UserAccount.PatientAccount;
import Business.UserAccount.UserAccount;
import Business.VitalSign.VitalSign;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author bhumika
 */
public class AddVitalSign extends javax.swing.JPanel {

    /** Creates new form AddVitalSign */
   private JPanel userProcessContainer;
   private UserAccount account;
   private Enterprise enterprise;
   private Date date;
   private PatientAccount patientAccount;
   
   
    public AddVitalSign(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        this.userProcessContainer= userProcessContainer;
        this.account= account;
        this.enterprise= enterprise;
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        bodyTemperatureTxtfield = new javax.swing.JTextField();
        vitalsignjBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        respiratoryRateTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        MusclepaincomboBox = new javax.swing.JComboBox<>();
        HeadacheComboBox = new javax.swing.JComboBox<>();
        coughtTypeComboBox = new javax.swing.JComboBox<>();

        jLabel6.setText("jLabel6");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyTemperatureTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodyTemperatureTxtfieldActionPerformed(evt);
            }
        });
        add(bodyTemperatureTxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, -1));

        vitalsignjBtn.setText("Add vital sign");
        vitalsignjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalsignjBtnActionPerformed(evt);
            }
        });
        add(vitalsignjBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel1.setText("BodyTemperature :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        add(respiratoryRateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        jLabel2.setText("Respiratory Rate :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Cough Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setText("Muscle Pain :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel7.setText("Headache :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MusclepaincomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        add(MusclepaincomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        HeadacheComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        add(HeadacheComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        coughtTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DRY COUGH", "WET COUGH", "CHRONIC COUGH" }));
        add(coughtTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bodyTemperatureTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodyTemperatureTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bodyTemperatureTxtfieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void vitalsignjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalsignjBtnActionPerformed
        Boolean b ;
        if( MusclepaincomboBox.getSelectedItem() == "YES")
        {
            b = true;
        }else{
            b = false;
        }
        Boolean a ;
        if( HeadacheComboBox.getSelectedItem() == "YES")
        {
            a = true;
        }else{
            a = false;
        }
        VitalSign v = account.getPatientAccount().getVitalSignHistory().createVitalSign(Float.parseFloat(bodyTemperatureTxtfield. getText()), Float.parseFloat(respiratoryRateTxtField. getText()), coughtTypeComboBox.getSelectedItem().toString(), b, a, java.time.LocalDateTime.now().toString(), "");
        System.out.println(v);        
       // patientAccount =(PatientAccount) account;
       
      // VitalSign v = ((PatientAccount) account).getVitalSignHistory().createVitalSign(Float.parseFloat(bodyTemperatureTxtfield. getText()), Float.parseFloat(respiratoryRateTxtField. getText()), coughtTypeComboBox.getSelectedItem().toString(), b, a, java.time.LocalDateTime.now().toString(), "");
       // patientAccount.getVitalSignHistory().createVitalSign(Float.parseFloat(bodyTemperatureTxtfield. getText()), Float.parseFloat(respiratoryRateTxtField. getText()), coughtTypeComboBox.getSelectedItem().toString(), b, a, java.time.LocalDateTime.now().toString(), "");
    }//GEN-LAST:event_vitalsignjBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HeadacheComboBox;
    private javax.swing.JComboBox<String> MusclepaincomboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bodyTemperatureTxtfield;
    private javax.swing.JComboBox<String> coughtTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField respiratoryRateTxtField;
    private javax.swing.JButton vitalsignjBtn;
    // End of variables declaration//GEN-END:variables

}
