/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_ManageAirliner;

import Business.Abstract.User;
import UserInterface.MainFrame;
import UserInterface.LogoutScreen;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class AirlinerMngArea extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel2
     */
    private User user;
    List<User> list;
    JPanel panelRight;

    public AirlinerMngArea(JPanel panelRight, User user) {
        initComponents();
        this.panelRight=panelRight;
        this.user = user;
        initialize();

    }

    private void initialize() {
        titaljLabel1.setText(titaljLabel1.getText() + " " + user.getUserName() + " !!!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirlineDetails = new javax.swing.JTable();
        btnCreateNewFlight = new javax.swing.JButton();
        btnUpdateFlight = new javax.swing.JButton();
        btnDeleteFlight = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        titaljLabel1 = new javax.swing.JLabel();

        tblAirlineDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight Number", "Source", "Destination", "Departure Time", "Arrival Time"
            }
        ));
        jScrollPane1.setViewportView(tblAirlineDetails);

        btnCreateNewFlight.setText("Create New Flight");
        btnCreateNewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewFlightActionPerformed(evt);
            }
        });

        btnUpdateFlight.setText("Update Airliner");
        btnUpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFlightActionPerformed(evt);
            }
        });

        btnDeleteFlight.setText("Delete Airliner");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        titaljLabel1.setText("Welcome ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCreateNewFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteFlight)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(btnUpdateFlight)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titaljLabel1)
                        .addGap(286, 286, 286)
                        .addComponent(btnLogout))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(titaljLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewFlight)
                    .addComponent(btnDeleteFlight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnUpdateFlight)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewFlightActionPerformed
        CardLayout layout = (CardLayout) panelRight.getLayout();
        panelRight.add(new CreateNewFlight(panelRight,user));
        layout.next(panelRight);

    }//GEN-LAST:event_btnCreateNewFlightActionPerformed

    private void btnUpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFlightActionPerformed
        CardLayout layout = (CardLayout) panelRight.getLayout();
        panelRight.add(new CreateNewFlight(panelRight,user));
        layout.next(panelRight);
    }//GEN-LAST:event_btnUpdateFlightActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        //MainFrame main= new MainFrame();
        CardLayout layout = (CardLayout) panelRight.getLayout();
        panelRight.add(new LogoutScreen(user));
        layout.next(panelRight);
        
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewFlight;
    private javax.swing.JButton btnDeleteFlight;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateFlight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirlineDetails;
    private javax.swing.JLabel titaljLabel1;
    // End of variables declaration//GEN-END:variables
}
